name: Nightly autoupdate

on:
  push:
    branches:
      - test-actions

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install bs4 pystache requests
      - name: Run autoupdater
        run: |
          ./autoupdater.sh
