name: Nightly autoupdate

on:
  push:
    branches:
      - test-actions2

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      # There are import isues with pystache with latest 3.9.
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install bs4 pystache requests zeep
      - name: Regenerate the library
        run: |
          python skautis_api_gen.py
      - name: Run import test
        run: |
          python regrtest.py
      - name: Commit and push changes (if any)
        run: |
          ./finish.sh
