name: PyPI deploy

on: 
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Auto commit')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Build a wheel and a source tarball
        run: |
          python -m pip install --user build
          python -m build --wheel --sdist --outdir dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/  # Delete this when the package is ready
